project_name: "${ProjectName}"
builds:
  -
    binary: "${ProjectName}"
    main: "./cmd/${ProjectName}"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "aix"
      - "darwin"
      - "dragonfly"
      - "freebsd"
      - "linux"
      - "netbsd"
      - "openbsd"
      - "plan9"
      - "solaris"
      - "windows"
    goarch:
      - "386"
      - "arm"
      - "arm64"
      - "amd64"
    ldflags:
      - -s
      - -w
      - -X "main.version={{.Version}}"
      - -X "main.commit={{.Commit}}"
      - -X "main.date={{.Date}}"
      - -X "main.author=${Author}"
      - -X "main.description=${Description}"
archives:
  - name_template: "${ProjectName}_{{.Version}}_{{.Os}}_{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}"
    format_overrides:
      - goos: "windows"
        format: "zip"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-next"
changelog:
  skip: true
nfpms:
  -
    id: "${ProjectName}"
    package_name: "${ProjectName}"
    homepage: "${HomePage}"
    maintainer: "${Author} <${AuthorEmail}>"
    description: "A template for golang"

    license: "MIT"

    # Formats to be generated.
    formats:
      - "deb"
      - "rpm"

    # Package epoch.
    # Defaults to empty.
    epoch: 1
dockers:
  -
    # GOOS of the built binaries/packages that should be used.
    goos: "linux"

    # GOARCH of the built binaries/packages that should be used.
    goarch: "amd64"

    # GOARM of the built binaries/packages that should be used.
    goarm: ''

    # IDs to filter the binaries/packages.
    ids:
      - "${ProjectName}"

    image_templates:
      - "${DockerImage}:{{.Tag}}"
      - "${DockerImage}:{{.Major}}"
      - "${DockerImage}:{{.Major}}.{{.Minor}}"
      - "${DockerImage}:latest"

    skip_push: false
    dockerfile: ".github/Dockerfile"

    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=BINARY=${ProjectName}"
      - "--platform=linux/amd64"
