package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/Eun/sshkeys"
	"github.com/asaskevich/govalidator"
	"golang.org/x/crypto/ssh"
)

var formatOption string
var outputOption string
var timeoutOption string
var concurrentOption int

// generated by goreleaser.
var version string
var commit string
var date string

const (
	authorizedKeys    = 1
	fingerprintMD5    = 2
	fingerprintSHA1   = 3
	fingerprintSHA256 = 4
)

const (
	outputConsole = 0
	outputJSON    = 1
)

func setupFlags() {
	flag.StringVar(&formatOption, "format", "authorized_keys", "")
	flag.StringVar(&formatOption, "f", "authorized_keys", "")
	flag.StringVar(&outputOption, "output", "", "")
	flag.StringVar(&outputOption, "o", "", "")
	flag.StringVar(&timeoutOption, "timeout", "60s", "")
	flag.StringVar(&timeoutOption, "t", "60s", "")
	flag.IntVar(&concurrentOption, "concurrent", 4, "") //nolint: gomnd // allow constant
	flag.IntVar(&concurrentOption, "c", 4, "")          //nolint: gomnd // allow constant
}

func printUsage() {
	fmt.Fprintf(os.Stderr, "Usage: %s [options] <host>\n", filepath.Base(os.Args[0]))
	fmt.Fprintln(os.Stderr, "Options:")
	fmt.Fprintln(os.Stderr, "    -format=authorized_keys       "+
		"Format to print the public keys, valid formats are: fingerprint, "+""+
		"sha1, sha256, md5, authorized_keys")
	fmt.Fprintln(os.Stderr, "    -output=console               Output format, valid formats are: console, json")
	fmt.Fprintln(os.Stderr, "    -timeout=60s                  Connection timeout")
	fmt.Fprintln(os.Stderr, "    -concurrent=4                 Concurrent workers")
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintf(os.Stderr, "sshkeys %s %s %s https://github.com/Eun/sshkeys", version, commit, date)
}

func main() {
	setupFlags()
	flag.Usage = printUsage
	flag.Parse()
	args := flag.Args()
	if len(args) == 0 {
		printUsage()
		os.Exit(1)
	}

	host := strings.TrimSpace(args[0])

	format := parseFormat(formatOption)
	output := parseOutput(outputOption)

	timeout, err := time.ParseDuration(timeoutOption)
	if err != nil {
		fmt.Fprintf(os.Stderr, "'%s' is not a duration\n", timeoutOption)
		os.Exit(1)
	}

	internalHost := host

	if !govalidator.IsDialString(host) {
		if !govalidator.IsHost(host) {
			exitWithMessage(output, host, fmt.Sprintf("'%s' is not a valid hostname", host))
			return
		}
		internalHost = net.JoinHostPort(internalHost, "22")
	}

	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	keys, err := sshkeys.GetKeys(ctx, internalHost, concurrentOption, sshkeys.DefaultKeyAlgorithms()...)
	cancel()
	if err != nil {
		exitWithMessage(output, host, err.Error())
		return
	}

	printableKeys := make([]string, 0, len(keys))
	for _, key := range keys {
		printableKey, err := keyToString(key, format)
		if err != nil {
			exitWithMessage(output, host, err.Error())
			return
		}
		addToResult := true
		for _, k := range printableKeys {
			if k == printableKey {
				addToResult = false
				break
			}
		}
		if !addToResult {
			continue
		}
		printableKeys = append(printableKeys, printableKey)
	}

	sort.Slice(printableKeys, func(i, j int) bool {
		return printableKeys[i] < printableKeys[j]
	})

	switch output {
	case outputJSON:
		err = json.NewEncoder(os.Stdout).Encode(struct {
			Host       string
			PublicKeys []string
		}{host, printableKeys})
		if err != nil {
			fmt.Fprintf(os.Stderr, "unable to encode json: %+v", err)
		}
	default:
		for i := 0; i < len(printableKeys); i++ {
			fmt.Println(printableKeys[i])
		}
	}
}

func exitWithMessage(output int, host, s string) {
	switch output {
	case outputJSON:
		err := json.NewEncoder(os.Stdout).Encode(struct {
			Host  string
			Error string
		}{host, s})
		if err != nil {
			fmt.Fprintf(os.Stderr, "unable to encode json: %+v", err)
		}
	default:
		fmt.Fprintln(os.Stderr, s)
	}
	os.Exit(1)
}

func keyToString(key ssh.PublicKey, format int) (string, error) {
	switch format {
	case fingerprintMD5:
		return sshkeys.FingerprintMD5(key)
	case fingerprintSHA1:
		return sshkeys.FingerprintSHA1(key)
	case fingerprintSHA256:
		return sshkeys.FingerprintSHA256(key)
	// case authorized_keys:
	//	fallthrough
	default:
		return sshkeys.AuthorizedKey(key)
	}
}

func parseFormat(format string) int {
	switch strings.ToLower(strings.TrimSpace(format)) {
	case "md5":
		return fingerprintMD5
	case "sha1":
		return fingerprintSHA1
	case "sha256":
		return fingerprintSHA256
	// case "authorized_keys":
	//	return authorizedKeys
	default:
		return authorizedKeys
	}
}

func parseOutput(output string) int {
	switch strings.ToLower(strings.TrimSpace(output)) {
	case "json":
		return outputJSON
	// case "console":
	//	fallthrough
	default:
		return outputConsole
	}
}
